name: final_projrct
description: Final year project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  google_fonts: ^2.1.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^3.1.8
  google_sign_in: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logback.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold_0.ttf
        - asset: fonts/Montserrat-Bold_2.ttf
        - asset: fonts/Montserrat-Medium_0.ttf
        - asset: fonts/Montserrat-Medium_2.ttf

